// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: hypixel.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DungeonClass int32

const (
	DungeonClass_DUNGEON_CLASS_BERSERK DungeonClass = 0
	DungeonClass_DUNGEON_CLASS_HEALER  DungeonClass = 1
	DungeonClass_DUNGEON_CLASS_ARCHER  DungeonClass = 2
	DungeonClass_DUNGEON_CLASS_MAGE    DungeonClass = 3
	DungeonClass_DUNGEON_CLASS_TANK    DungeonClass = 4
)

// Enum value maps for DungeonClass.
var (
	DungeonClass_name = map[int32]string{
		0: "DUNGEON_CLASS_BERSERK",
		1: "DUNGEON_CLASS_HEALER",
		2: "DUNGEON_CLASS_ARCHER",
		3: "DUNGEON_CLASS_MAGE",
		4: "DUNGEON_CLASS_TANK",
	}
	DungeonClass_value = map[string]int32{
		"DUNGEON_CLASS_BERSERK": 0,
		"DUNGEON_CLASS_HEALER":  1,
		"DUNGEON_CLASS_ARCHER":  2,
		"DUNGEON_CLASS_MAGE":    3,
		"DUNGEON_CLASS_TANK":    4,
	}
)

func (x DungeonClass) Enum() *DungeonClass {
	p := new(DungeonClass)
	*p = x
	return p
}

func (x DungeonClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DungeonClass) Descriptor() protoreflect.EnumDescriptor {
	return file_hypixel_proto_enumTypes[0].Descriptor()
}

func (DungeonClass) Type() protoreflect.EnumType {
	return &file_hypixel_proto_enumTypes[0]
}

func (x DungeonClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DungeonClass.Descriptor instead.
func (DungeonClass) EnumDescriptor() ([]byte, []int) {
	return file_hypixel_proto_rawDescGZIP(), []int{0}
}

type DungeonMode int32

const (
	DungeonMode_DUNGEON_MODE_CATACOMBS        DungeonMode = 0
	DungeonMode_DUNGEON_MODE_MASTER_CATACOMBS DungeonMode = 1
)

// Enum value maps for DungeonMode.
var (
	DungeonMode_name = map[int32]string{
		0: "DUNGEON_MODE_CATACOMBS",
		1: "DUNGEON_MODE_MASTER_CATACOMBS",
	}
	DungeonMode_value = map[string]int32{
		"DUNGEON_MODE_CATACOMBS":        0,
		"DUNGEON_MODE_MASTER_CATACOMBS": 1,
	}
)

func (x DungeonMode) Enum() *DungeonMode {
	p := new(DungeonMode)
	*p = x
	return p
}

func (x DungeonMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DungeonMode) Descriptor() protoreflect.EnumDescriptor {
	return file_hypixel_proto_enumTypes[1].Descriptor()
}

func (DungeonMode) Type() protoreflect.EnumType {
	return &file_hypixel_proto_enumTypes[1]
}

func (x DungeonMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DungeonMode.Descriptor instead.
func (DungeonMode) EnumDescriptor() ([]byte, []int) {
	return file_hypixel_proto_rawDescGZIP(), []int{1}
}

type MojangProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MojangProfile) Reset() {
	*x = MojangProfile{}
	mi := &file_hypixel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MojangProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MojangProfile) ProtoMessage() {}

func (x *MojangProfile) ProtoReflect() protoreflect.Message {
	mi := &file_hypixel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MojangProfile.ProtoReflect.Descriptor instead.
func (*MojangProfile) Descriptor() ([]byte, []int) {
	return file_hypixel_proto_rawDescGZIP(), []int{0}
}

func (x *MojangProfile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *MojangProfile) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type SkyBlockProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mojang        *MojangProfile         `protobuf:"bytes,1,opt,name=mojang,proto3" json:"mojang,omitempty"`
	Profile       string                 `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkyBlockProfile) Reset() {
	*x = SkyBlockProfile{}
	mi := &file_hypixel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkyBlockProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkyBlockProfile) ProtoMessage() {}

func (x *SkyBlockProfile) ProtoReflect() protoreflect.Message {
	mi := &file_hypixel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkyBlockProfile.ProtoReflect.Descriptor instead.
func (*SkyBlockProfile) Descriptor() ([]byte, []int) {
	return file_hypixel_proto_rawDescGZIP(), []int{1}
}

func (x *SkyBlockProfile) GetMojang() *MojangProfile {
	if x != nil {
		return x.Mojang
	}
	return nil
}

func (x *SkyBlockProfile) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

type SkyBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Profile       string                 `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkyBlockRequest) Reset() {
	*x = SkyBlockRequest{}
	mi := &file_hypixel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkyBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkyBlockRequest) ProtoMessage() {}

func (x *SkyBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hypixel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkyBlockRequest.ProtoReflect.Descriptor instead.
func (*SkyBlockRequest) Descriptor() ([]byte, []int) {
	return file_hypixel_proto_rawDescGZIP(), []int{2}
}

func (x *SkyBlockRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SkyBlockRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

type NetworthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         float64                `protobuf:"fixed64,1,opt,name=total,proto3" json:"total,omitempty"`
	Unsoulbound   float64                `protobuf:"fixed64,2,opt,name=unsoulbound,proto3" json:"unsoulbound,omitempty"`
	Profile       *SkyBlockProfile       `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworthResponse) Reset() {
	*x = NetworthResponse{}
	mi := &file_hypixel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworthResponse) ProtoMessage() {}

func (x *NetworthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hypixel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworthResponse.ProtoReflect.Descriptor instead.
func (*NetworthResponse) Descriptor() ([]byte, []int) {
	return file_hypixel_proto_rawDescGZIP(), []int{3}
}

func (x *NetworthResponse) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *NetworthResponse) GetUnsoulbound() float64 {
	if x != nil {
		return x.Unsoulbound
	}
	return 0
}

func (x *NetworthResponse) GetProfile() *SkyBlockProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type FarmingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FarmingLevel  float64                `protobuf:"fixed64,1,opt,name=farming_level,json=farmingLevel,proto3" json:"farming_level,omitempty"`
	GardenLevel   float64                `protobuf:"fixed64,2,opt,name=garden_level,json=gardenLevel,proto3" json:"garden_level,omitempty"`
	FarmingXp     float64                `protobuf:"fixed64,3,opt,name=farming_xp,json=farmingXp,proto3" json:"farming_xp,omitempty"`
	GardenXp      float64                `protobuf:"fixed64,4,opt,name=garden_xp,json=gardenXp,proto3" json:"garden_xp,omitempty"`
	Weight        float64                `protobuf:"fixed64,5,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FarmingResponse) Reset() {
	*x = FarmingResponse{}
	mi := &file_hypixel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FarmingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FarmingResponse) ProtoMessage() {}

func (x *FarmingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hypixel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FarmingResponse.ProtoReflect.Descriptor instead.
func (*FarmingResponse) Descriptor() ([]byte, []int) {
	return file_hypixel_proto_rawDescGZIP(), []int{4}
}

func (x *FarmingResponse) GetFarmingLevel() float64 {
	if x != nil {
		return x.FarmingLevel
	}
	return 0
}

func (x *FarmingResponse) GetGardenLevel() float64 {
	if x != nil {
		return x.GardenLevel
	}
	return 0
}

func (x *FarmingResponse) GetFarmingXp() float64 {
	if x != nil {
		return x.FarmingXp
	}
	return 0
}

func (x *FarmingResponse) GetGardenXp() float64 {
	if x != nil {
		return x.GardenXp
	}
	return 0
}

func (x *FarmingResponse) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type DungeonClassLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DungeonClass  DungeonClass           `protobuf:"varint,1,opt,name=dungeon_class,json=dungeonClass,proto3,enum=DungeonClass" json:"dungeon_class,omitempty"`
	Level         float64                `protobuf:"fixed64,2,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DungeonClassLevel) Reset() {
	*x = DungeonClassLevel{}
	mi := &file_hypixel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DungeonClassLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DungeonClassLevel) ProtoMessage() {}

func (x *DungeonClassLevel) ProtoReflect() protoreflect.Message {
	mi := &file_hypixel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DungeonClassLevel.ProtoReflect.Descriptor instead.
func (*DungeonClassLevel) Descriptor() ([]byte, []int) {
	return file_hypixel_proto_rawDescGZIP(), []int{5}
}

func (x *DungeonClassLevel) GetDungeonClass() DungeonClass {
	if x != nil {
		return x.DungeonClass
	}
	return DungeonClass_DUNGEON_CLASS_BERSERK
}

func (x *DungeonClassLevel) GetLevel() float64 {
	if x != nil {
		return x.Level
	}
	return 0
}

type DungeonFloorStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          DungeonMode            `protobuf:"varint,1,opt,name=mode,proto3,enum=DungeonMode" json:"mode,omitempty"`
	Floor         uint32                 `protobuf:"varint,2,opt,name=floor,proto3" json:"floor,omitempty"`
	Completions   float64                `protobuf:"fixed64,3,opt,name=completions,proto3" json:"completions,omitempty"`
	PersonalBest  *float64               `protobuf:"fixed64,4,opt,name=personal_best,json=personalBest,proto3,oneof" json:"personal_best,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DungeonFloorStats) Reset() {
	*x = DungeonFloorStats{}
	mi := &file_hypixel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DungeonFloorStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DungeonFloorStats) ProtoMessage() {}

func (x *DungeonFloorStats) ProtoReflect() protoreflect.Message {
	mi := &file_hypixel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DungeonFloorStats.ProtoReflect.Descriptor instead.
func (*DungeonFloorStats) Descriptor() ([]byte, []int) {
	return file_hypixel_proto_rawDescGZIP(), []int{6}
}

func (x *DungeonFloorStats) GetMode() DungeonMode {
	if x != nil {
		return x.Mode
	}
	return DungeonMode_DUNGEON_MODE_CATACOMBS
}

func (x *DungeonFloorStats) GetFloor() uint32 {
	if x != nil {
		return x.Floor
	}
	return 0
}

func (x *DungeonFloorStats) GetCompletions() float64 {
	if x != nil {
		return x.Completions
	}
	return 0
}

func (x *DungeonFloorStats) GetPersonalBest() float64 {
	if x != nil && x.PersonalBest != nil {
		return *x.PersonalBest
	}
	return 0
}

type DungeonsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Profile            *SkyBlockProfile       `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	ClassAverage       float64                `protobuf:"fixed64,2,opt,name=class_average,json=classAverage,proto3" json:"class_average,omitempty"`
	CatacombsLevel     float64                `protobuf:"fixed64,3,opt,name=catacombs_level,json=catacombsLevel,proto3" json:"catacombs_level,omitempty"`
	SelectedClass      *DungeonClass          `protobuf:"varint,4,opt,name=selected_class,json=selectedClass,proto3,enum=DungeonClass,oneof" json:"selected_class,omitempty"`
	SelectedClassLevel float64                `protobuf:"fixed64,5,opt,name=selected_class_level,json=selectedClassLevel,proto3" json:"selected_class_level,omitempty"`
	SecretsFound       float64                `protobuf:"fixed64,6,opt,name=secrets_found,json=secretsFound,proto3" json:"secrets_found,omitempty"`
	Classes            []*DungeonClassLevel   `protobuf:"bytes,7,rep,name=classes,proto3" json:"classes,omitempty"`
	Floors             []*DungeonFloorStats   `protobuf:"bytes,8,rep,name=floors,proto3" json:"floors,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DungeonsResponse) Reset() {
	*x = DungeonsResponse{}
	mi := &file_hypixel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DungeonsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DungeonsResponse) ProtoMessage() {}

func (x *DungeonsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hypixel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DungeonsResponse.ProtoReflect.Descriptor instead.
func (*DungeonsResponse) Descriptor() ([]byte, []int) {
	return file_hypixel_proto_rawDescGZIP(), []int{7}
}

func (x *DungeonsResponse) GetProfile() *SkyBlockProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *DungeonsResponse) GetClassAverage() float64 {
	if x != nil {
		return x.ClassAverage
	}
	return 0
}

func (x *DungeonsResponse) GetCatacombsLevel() float64 {
	if x != nil {
		return x.CatacombsLevel
	}
	return 0
}

func (x *DungeonsResponse) GetSelectedClass() DungeonClass {
	if x != nil && x.SelectedClass != nil {
		return *x.SelectedClass
	}
	return DungeonClass_DUNGEON_CLASS_BERSERK
}

func (x *DungeonsResponse) GetSelectedClassLevel() float64 {
	if x != nil {
		return x.SelectedClassLevel
	}
	return 0
}

func (x *DungeonsResponse) GetSecretsFound() float64 {
	if x != nil {
		return x.SecretsFound
	}
	return 0
}

func (x *DungeonsResponse) GetClasses() []*DungeonClassLevel {
	if x != nil {
		return x.Classes
	}
	return nil
}

func (x *DungeonsResponse) GetFloors() []*DungeonFloorStats {
	if x != nil {
		return x.Floors
	}
	return nil
}

var File_hypixel_proto protoreflect.FileDescriptor

const file_hypixel_proto_rawDesc = "" +
	"\n" +
	"\rhypixel.proto\"?\n" +
	"\rMojangProfile\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\"S\n" +
	"\x0fSkyBlockProfile\x12&\n" +
	"\x06mojang\x18\x01 \x01(\v2\x0e.MojangProfileR\x06mojang\x12\x18\n" +
	"\aprofile\x18\x02 \x01(\tR\aprofile\"G\n" +
	"\x0fSkyBlockRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x18\n" +
	"\aprofile\x18\x02 \x01(\tR\aprofile\"v\n" +
	"\x10NetworthResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x01R\x05total\x12 \n" +
	"\vunsoulbound\x18\x02 \x01(\x01R\vunsoulbound\x12*\n" +
	"\aprofile\x18\x03 \x01(\v2\x10.SkyBlockProfileR\aprofile\"\xad\x01\n" +
	"\x0fFarmingResponse\x12#\n" +
	"\rfarming_level\x18\x01 \x01(\x01R\ffarmingLevel\x12!\n" +
	"\fgarden_level\x18\x02 \x01(\x01R\vgardenLevel\x12\x1d\n" +
	"\n" +
	"farming_xp\x18\x03 \x01(\x01R\tfarmingXp\x12\x1b\n" +
	"\tgarden_xp\x18\x04 \x01(\x01R\bgardenXp\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x01R\x06weight\"]\n" +
	"\x11DungeonClassLevel\x122\n" +
	"\rdungeon_class\x18\x01 \x01(\x0e2\r.DungeonClassR\fdungeonClass\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x01R\x05level\"\xa9\x01\n" +
	"\x11DungeonFloorStats\x12 \n" +
	"\x04mode\x18\x01 \x01(\x0e2\f.DungeonModeR\x04mode\x12\x14\n" +
	"\x05floor\x18\x02 \x01(\rR\x05floor\x12 \n" +
	"\vcompletions\x18\x03 \x01(\x01R\vcompletions\x12(\n" +
	"\rpersonal_best\x18\x04 \x01(\x01H\x00R\fpersonalBest\x88\x01\x01B\x10\n" +
	"\x0e_personal_best\"\x8b\x03\n" +
	"\x10DungeonsResponse\x12*\n" +
	"\aprofile\x18\x01 \x01(\v2\x10.SkyBlockProfileR\aprofile\x12#\n" +
	"\rclass_average\x18\x02 \x01(\x01R\fclassAverage\x12'\n" +
	"\x0fcatacombs_level\x18\x03 \x01(\x01R\x0ecatacombsLevel\x129\n" +
	"\x0eselected_class\x18\x04 \x01(\x0e2\r.DungeonClassH\x00R\rselectedClass\x88\x01\x01\x120\n" +
	"\x14selected_class_level\x18\x05 \x01(\x01R\x12selectedClassLevel\x12#\n" +
	"\rsecrets_found\x18\x06 \x01(\x01R\fsecretsFound\x12,\n" +
	"\aclasses\x18\a \x03(\v2\x12.DungeonClassLevelR\aclasses\x12*\n" +
	"\x06floors\x18\b \x03(\v2\x12.DungeonFloorStatsR\x06floorsB\x11\n" +
	"\x0f_selected_class*\x8d\x01\n" +
	"\fDungeonClass\x12\x19\n" +
	"\x15DUNGEON_CLASS_BERSERK\x10\x00\x12\x18\n" +
	"\x14DUNGEON_CLASS_HEALER\x10\x01\x12\x18\n" +
	"\x14DUNGEON_CLASS_ARCHER\x10\x02\x12\x16\n" +
	"\x12DUNGEON_CLASS_MAGE\x10\x03\x12\x16\n" +
	"\x12DUNGEON_CLASS_TANK\x10\x04*L\n" +
	"\vDungeonMode\x12\x1a\n" +
	"\x16DUNGEON_MODE_CATACOMBS\x10\x00\x12!\n" +
	"\x1dDUNGEON_MODE_MASTER_CATACOMBS\x10\x012\xa3\x01\n" +
	"\aHypixel\x122\n" +
	"\vGetNetworth\x12\x10.SkyBlockRequest\x1a\x11.NetworthResponse\x122\n" +
	"\vGetDungeons\x12\x10.SkyBlockRequest\x1a\x11.DungeonsResponse\x120\n" +
	"\n" +
	"GetFarming\x12\x10.SkyBlockRequest\x1a\x10.FarmingResponseB*Z(github.com/guild-link/hypixel-grpc/protob\x06proto3"

var (
	file_hypixel_proto_rawDescOnce sync.Once
	file_hypixel_proto_rawDescData []byte
)

func file_hypixel_proto_rawDescGZIP() []byte {
	file_hypixel_proto_rawDescOnce.Do(func() {
		file_hypixel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hypixel_proto_rawDesc), len(file_hypixel_proto_rawDesc)))
	})
	return file_hypixel_proto_rawDescData
}

var file_hypixel_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_hypixel_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_hypixel_proto_goTypes = []any{
	(DungeonClass)(0),         // 0: DungeonClass
	(DungeonMode)(0),          // 1: DungeonMode
	(*MojangProfile)(nil),     // 2: MojangProfile
	(*SkyBlockProfile)(nil),   // 3: SkyBlockProfile
	(*SkyBlockRequest)(nil),   // 4: SkyBlockRequest
	(*NetworthResponse)(nil),  // 5: NetworthResponse
	(*FarmingResponse)(nil),   // 6: FarmingResponse
	(*DungeonClassLevel)(nil), // 7: DungeonClassLevel
	(*DungeonFloorStats)(nil), // 8: DungeonFloorStats
	(*DungeonsResponse)(nil),  // 9: DungeonsResponse
}
var file_hypixel_proto_depIdxs = []int32{
	2,  // 0: SkyBlockProfile.mojang:type_name -> MojangProfile
	3,  // 1: NetworthResponse.profile:type_name -> SkyBlockProfile
	0,  // 2: DungeonClassLevel.dungeon_class:type_name -> DungeonClass
	1,  // 3: DungeonFloorStats.mode:type_name -> DungeonMode
	3,  // 4: DungeonsResponse.profile:type_name -> SkyBlockProfile
	0,  // 5: DungeonsResponse.selected_class:type_name -> DungeonClass
	7,  // 6: DungeonsResponse.classes:type_name -> DungeonClassLevel
	8,  // 7: DungeonsResponse.floors:type_name -> DungeonFloorStats
	4,  // 8: Hypixel.GetNetworth:input_type -> SkyBlockRequest
	4,  // 9: Hypixel.GetDungeons:input_type -> SkyBlockRequest
	4,  // 10: Hypixel.GetFarming:input_type -> SkyBlockRequest
	5,  // 11: Hypixel.GetNetworth:output_type -> NetworthResponse
	9,  // 12: Hypixel.GetDungeons:output_type -> DungeonsResponse
	6,  // 13: Hypixel.GetFarming:output_type -> FarmingResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_hypixel_proto_init() }
func file_hypixel_proto_init() {
	if File_hypixel_proto != nil {
		return
	}
	file_hypixel_proto_msgTypes[6].OneofWrappers = []any{}
	file_hypixel_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hypixel_proto_rawDesc), len(file_hypixel_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hypixel_proto_goTypes,
		DependencyIndexes: file_hypixel_proto_depIdxs,
		EnumInfos:         file_hypixel_proto_enumTypes,
		MessageInfos:      file_hypixel_proto_msgTypes,
	}.Build()
	File_hypixel_proto = out.File
	file_hypixel_proto_goTypes = nil
	file_hypixel_proto_depIdxs = nil
}
