// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: hypixel.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Hypixel_GetNetworth_FullMethodName = "/Hypixel/GetNetworth"
	Hypixel_GetDungeons_FullMethodName = "/Hypixel/GetDungeons"
	Hypixel_GetFarming_FullMethodName  = "/Hypixel/GetFarming"
)

// HypixelClient is the client API for Hypixel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HypixelClient interface {
	GetNetworth(ctx context.Context, in *SkyBlockRequest, opts ...grpc.CallOption) (*NetworthResponse, error)
	GetDungeons(ctx context.Context, in *SkyBlockRequest, opts ...grpc.CallOption) (*DungeonsResponse, error)
	GetFarming(ctx context.Context, in *SkyBlockRequest, opts ...grpc.CallOption) (*FarmingResponse, error)
}

type hypixelClient struct {
	cc grpc.ClientConnInterface
}

func NewHypixelClient(cc grpc.ClientConnInterface) HypixelClient {
	return &hypixelClient{cc}
}

func (c *hypixelClient) GetNetworth(ctx context.Context, in *SkyBlockRequest, opts ...grpc.CallOption) (*NetworthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworthResponse)
	err := c.cc.Invoke(ctx, Hypixel_GetNetworth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hypixelClient) GetDungeons(ctx context.Context, in *SkyBlockRequest, opts ...grpc.CallOption) (*DungeonsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DungeonsResponse)
	err := c.cc.Invoke(ctx, Hypixel_GetDungeons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hypixelClient) GetFarming(ctx context.Context, in *SkyBlockRequest, opts ...grpc.CallOption) (*FarmingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FarmingResponse)
	err := c.cc.Invoke(ctx, Hypixel_GetFarming_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HypixelServer is the server API for Hypixel service.
// All implementations must embed UnimplementedHypixelServer
// for forward compatibility.
type HypixelServer interface {
	GetNetworth(context.Context, *SkyBlockRequest) (*NetworthResponse, error)
	GetDungeons(context.Context, *SkyBlockRequest) (*DungeonsResponse, error)
	GetFarming(context.Context, *SkyBlockRequest) (*FarmingResponse, error)
	mustEmbedUnimplementedHypixelServer()
}

// UnimplementedHypixelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHypixelServer struct{}

func (UnimplementedHypixelServer) GetNetworth(context.Context, *SkyBlockRequest) (*NetworthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNetworth not implemented")
}
func (UnimplementedHypixelServer) GetDungeons(context.Context, *SkyBlockRequest) (*DungeonsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDungeons not implemented")
}
func (UnimplementedHypixelServer) GetFarming(context.Context, *SkyBlockRequest) (*FarmingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFarming not implemented")
}
func (UnimplementedHypixelServer) mustEmbedUnimplementedHypixelServer() {}
func (UnimplementedHypixelServer) testEmbeddedByValue()                 {}

// UnsafeHypixelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HypixelServer will
// result in compilation errors.
type UnsafeHypixelServer interface {
	mustEmbedUnimplementedHypixelServer()
}

func RegisterHypixelServer(s grpc.ServiceRegistrar, srv HypixelServer) {
	// If the following call panics, it indicates UnimplementedHypixelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Hypixel_ServiceDesc, srv)
}

func _Hypixel_GetNetworth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkyBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HypixelServer).GetNetworth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hypixel_GetNetworth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HypixelServer).GetNetworth(ctx, req.(*SkyBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hypixel_GetDungeons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkyBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HypixelServer).GetDungeons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hypixel_GetDungeons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HypixelServer).GetDungeons(ctx, req.(*SkyBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hypixel_GetFarming_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkyBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HypixelServer).GetFarming(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hypixel_GetFarming_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HypixelServer).GetFarming(ctx, req.(*SkyBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Hypixel_ServiceDesc is the grpc.ServiceDesc for Hypixel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hypixel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Hypixel",
	HandlerType: (*HypixelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNetworth",
			Handler:    _Hypixel_GetNetworth_Handler,
		},
		{
			MethodName: "GetDungeons",
			Handler:    _Hypixel_GetDungeons_Handler,
		},
		{
			MethodName: "GetFarming",
			Handler:    _Hypixel_GetFarming_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hypixel.proto",
}
