// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: hypixel.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SkyBlock_GetNetworth_FullMethodName = "/hypixel.SkyBlock/GetNetworth"
	SkyBlock_GetDungeons_FullMethodName = "/hypixel.SkyBlock/GetDungeons"
	SkyBlock_GetFarming_FullMethodName  = "/hypixel.SkyBlock/GetFarming"
)

// SkyBlockClient is the client API for SkyBlock service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SkyBlockClient interface {
	GetNetworth(ctx context.Context, in *SkyBlockRequest, opts ...grpc.CallOption) (*NetworthResponse, error)
	GetDungeons(ctx context.Context, in *SkyBlockRequest, opts ...grpc.CallOption) (*DungeonsResponse, error)
	GetFarming(ctx context.Context, in *SkyBlockRequest, opts ...grpc.CallOption) (*FarmingResponse, error)
}

type skyBlockClient struct {
	cc grpc.ClientConnInterface
}

func NewSkyBlockClient(cc grpc.ClientConnInterface) SkyBlockClient {
	return &skyBlockClient{cc}
}

func (c *skyBlockClient) GetNetworth(ctx context.Context, in *SkyBlockRequest, opts ...grpc.CallOption) (*NetworthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworthResponse)
	err := c.cc.Invoke(ctx, SkyBlock_GetNetworth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skyBlockClient) GetDungeons(ctx context.Context, in *SkyBlockRequest, opts ...grpc.CallOption) (*DungeonsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DungeonsResponse)
	err := c.cc.Invoke(ctx, SkyBlock_GetDungeons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skyBlockClient) GetFarming(ctx context.Context, in *SkyBlockRequest, opts ...grpc.CallOption) (*FarmingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FarmingResponse)
	err := c.cc.Invoke(ctx, SkyBlock_GetFarming_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SkyBlockServer is the server API for SkyBlock service.
// All implementations must embed UnimplementedSkyBlockServer
// for forward compatibility.
type SkyBlockServer interface {
	GetNetworth(context.Context, *SkyBlockRequest) (*NetworthResponse, error)
	GetDungeons(context.Context, *SkyBlockRequest) (*DungeonsResponse, error)
	GetFarming(context.Context, *SkyBlockRequest) (*FarmingResponse, error)
	mustEmbedUnimplementedSkyBlockServer()
}

// UnimplementedSkyBlockServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSkyBlockServer struct{}

func (UnimplementedSkyBlockServer) GetNetworth(context.Context, *SkyBlockRequest) (*NetworthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNetworth not implemented")
}
func (UnimplementedSkyBlockServer) GetDungeons(context.Context, *SkyBlockRequest) (*DungeonsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDungeons not implemented")
}
func (UnimplementedSkyBlockServer) GetFarming(context.Context, *SkyBlockRequest) (*FarmingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFarming not implemented")
}
func (UnimplementedSkyBlockServer) mustEmbedUnimplementedSkyBlockServer() {}
func (UnimplementedSkyBlockServer) testEmbeddedByValue()                  {}

// UnsafeSkyBlockServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SkyBlockServer will
// result in compilation errors.
type UnsafeSkyBlockServer interface {
	mustEmbedUnimplementedSkyBlockServer()
}

func RegisterSkyBlockServer(s grpc.ServiceRegistrar, srv SkyBlockServer) {
	// If the following call panics, it indicates UnimplementedSkyBlockServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SkyBlock_ServiceDesc, srv)
}

func _SkyBlock_GetNetworth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkyBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyBlockServer).GetNetworth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkyBlock_GetNetworth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyBlockServer).GetNetworth(ctx, req.(*SkyBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkyBlock_GetDungeons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkyBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyBlockServer).GetDungeons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkyBlock_GetDungeons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyBlockServer).GetDungeons(ctx, req.(*SkyBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkyBlock_GetFarming_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkyBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyBlockServer).GetFarming(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkyBlock_GetFarming_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyBlockServer).GetFarming(ctx, req.(*SkyBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SkyBlock_ServiceDesc is the grpc.ServiceDesc for SkyBlock service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SkyBlock_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hypixel.SkyBlock",
	HandlerType: (*SkyBlockServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNetworth",
			Handler:    _SkyBlock_GetNetworth_Handler,
		},
		{
			MethodName: "GetDungeons",
			Handler:    _SkyBlock_GetDungeons_Handler,
		},
		{
			MethodName: "GetFarming",
			Handler:    _SkyBlock_GetFarming_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hypixel.proto",
}
